"""
train_detector.py — Phase D detector training

Trains YOLOv8n on CITRON crop data (crop_mode) or stitched images (stitched_mode).

Usage:
    python src/detection/train_detector.py --config configs/detector.yaml [--mode crop_mode]

Outputs (under outputs/detection/{mode}/):
    weights/best.pt
    training_summary.json
    run_config.yaml
"""

import sys
import os
import argparse
import json
from pathlib import Path

import yaml

_HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(_HERE.parent.parent))
try:
    from src.common.io_utils import get_logger
    from src.common.config_utils import load_yaml, save_json, copy_config
    from src.common.seed_utils import set_all_seeds
except ImportError as e:
    print(f"Error importing modules: {e}")
    print("Make sure to run this script from the project root directory.")
    sys.exit(1)
LOG = get_logger("train_detector")
SEED = 42


def build_yolo_dataset_yaml(
    train_img_paths: list[str],
    val_img_paths: list[str],
    class_names: list[str],
    out_yaml: str | Path,
    train_txt: str | Path,
    val_txt: str | Path,
) -> None:
    """Write YOLO dataset YAML and image list txt files."""
    Path(train_txt).parent.mkdir(parents=True, exist_ok=True)
    with open(train_txt, "w") as f:
        f.write("\n".join(train_img_paths))
    with open(val_txt, "w") as f:
        f.write("\n".join(val_img_paths))

    data = {
        "train": str(Path(train_txt).resolve()),
        "val": str(Path(val_txt).resolve()),
        "nc": len(class_names),
        "names": class_names,
    }
    Path(out_yaml).parent.mkdir(parents=True, exist_ok=True)
    with open(out_yaml, "w") as f:
        yaml.dump(data, f, default_flow_style=False)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--config", default="configs/detector.yaml")
    parser.add_argument(
        "--mode", choices=["crop_mode", "stitched_mode"], default="crop_mode")
    parser.add_argument("--force", action="store_true")
    args = parser.parse_args()

    cfg = load_yaml(args.config)
    mode = args.mode
    set_all_seeds(SEED)

    import pandas as pd
    split_dir = Path(cfg["data"]["split_dir"])
    train_csv = split_dir / cfg["data"]["train_csv"]
    val_csv = split_dir / cfg["data"]["val_csv"]

    train_df = pd.read_csv(train_csv)
    val_df = pd.read_csv(val_csv)

    # Remap stored absolute paths to the configured crop_dir (handles stale paths
    # from a previous session, e.g. /kaggle/working/ → /kaggle/input/...).
    _crop_dir = cfg["data"].get("crop_dir")
    if _crop_dir:
        _crop_dir = Path(_crop_dir)
        for _df in (train_df, val_df):
            if "image_path" in _df.columns:
                _df["image_path"] = _df["image_path"].apply(
                    lambda p: str(
                        _crop_dir / Path(p).name) if isinstance(p, str) and p else p
                )

    if mode == "crop_mode":
        train_imgs = train_df["image_path"].tolist()
        val_imgs = val_df["image_path"].tolist()
    else:
        # stitched_mode: use stitched images (generated by fusion engine beforehand)
        stitched_dir = Path(cfg["data"]["stitched_dir"])
        train_scene_ids = train_df["scene_id"].unique().tolist()
        val_scene_ids = val_df["scene_id"].unique().tolist()
        train_imgs = [str(p) for sid in train_scene_ids
                      for p in stitched_dir.glob(f"{sid}_A4_*.jpg")]
        val_imgs = [str(p) for sid in val_scene_ids
                    for p in stitched_dir.glob(f"{sid}_A4_*.jpg")]

    out_dir = Path(cfg["output_root"]) / mode
    out_dir.mkdir(parents=True, exist_ok=True)

    yolo_yaml = out_dir / "kitti_citron.yaml"
    train_txt = out_dir / "train.txt"
    val_txt = out_dir / "val.txt"

    build_yolo_dataset_yaml(
        train_imgs, val_imgs,
        cfg["classes"],
        yolo_yaml, train_txt, val_txt,
    )

    LOG.info(f"Mode: {mode} | Train: {len(train_imgs)} | Val: {len(val_imgs)}")
    LOG.info(f"YOLO data YAML: {yolo_yaml}")

    weights_path = out_dir / "weights" / "best.pt"
    if weights_path.exists() and not args.force:
        LOG.info(
            f"Weights already exist: {weights_path}. Use --force to retrain.")
        return

    from ultralytics import YOLO
    model = YOLO(cfg["model"] + ".pt")

    train_cfg = cfg["training"]
    results = model.train(
        data=str(yolo_yaml),
        epochs=train_cfg["epochs"],
        patience=train_cfg["patience"],
        batch=train_cfg["batch"],
        imgsz=train_cfg["imgsz"],
        device=train_cfg["device"],
        workers=train_cfg["workers"],
        mixup=train_cfg["mixup"],
        save=train_cfg["save"],
        plots=train_cfg["plots"],
        project=str(out_dir),
        name="train",
        seed=SEED,
        exist_ok=True,
    )

    summary = {
        "mode": mode,
        "n_train": len(train_imgs),
        "n_val": len(val_imgs),
        "epochs_trained": train_cfg["epochs"],
        "model": cfg["model"],
    }
    save_json(summary, out_dir / "training_summary.json")
    copy_config(args.config, out_dir)
    LOG.info("Training complete.")


if __name__ == "__main__":
    main()
